### ISSUE TITLE
Possibility of compressing non-MoE LLM

### ISSUE THREAD

**Issue by NicoNico6** [IST-DASLab/qmoe#3]
Dear authors, this work is really solid which drives my interest in the possibility of further compressing non-MoE LLM like LLama, would you mind sharing some ideas for this? Would it be possible to compress LLama-7B with the same method? Will LLama-7b be different to  base128 (7B params)?

**Comment by Godofnothing** [comment]
@NicoNico6  Llama-7B would become unusable with such an aggressive quantization. Note, that in the core of the method is GPTQ algorithm; the contribution of this work is scaling GPTQ to Trillion-param models together with further compression of ternary quantization.

**Comment by NicoNico6** [comment]
@Godofnothing Thanks a lot for your kind feedback. In the paper section 5.1 and Table 5, the authors have reported the 7B switch-base128 quantization results, which seem to be quite good (PPL: 1.73 for BF16, 1.76 for 2-bit, and 1.93 for Ternary). 

`Our primary target is the very largest variant, c2048, with around 1.6 trillion parameters, but we also consider the comparatively small base128 (7B params) and large128 (26B params) versions for testing and ablations.`

Now that  switch-base128 and LLama 7B have similar model size, what is the core difference between switch-base128 quantization and LLama-7B quantization?

**Comment by efrantar** [comment]
Hi, you can indeed apply the [GPTQ](https://github.com/IST-DASLab/gptq) algorithm also to LLama, however such aggressive quantization is likely not possible on this model. We provide some discussion on why MoEs are easier to compress in the paper.

![image](https://github.com/IST-DASLab/qmoe/assets/24566677/bf50d556-0788-441d-bb88-e74bf8535782)

It is also worth noting that the 7B MoE has the inference cost of a 200M parameter dense model, which it is designed to outperform in terms of quality. In fact, the main idea behind MoEs is to achieve higher inference speed (at the same accuracy) by having (much) more parameters (but using only subsets of them), which likely also leads to higher compressibility.

**Comment by NicoNico6** [comment]
Thanks a lot for your kind answer and the solid work in this direction. I am really interested in the low-bit compression direction, and your efficient Cuda implementation of the sub1-bit coding really helps a lot for my current research. The answer has basically solved my question.
